In [1]:
import os
import weaviate
import weaviate.classes.config as wvc

from dotenv import load_dotenv
from openai import OpenAI

import requests
from bs4 import BeautifulSoup
import tiktoken

In [2]:
load_dotenv(r'.env')

True

In [3]:
def get_content(url):
    response = requests.get(url)

    soup = BeautifulSoup(response.text, 'html.parser')

    for script_or_style in soup(["script", "style", "header", "footer", "nav"]):
        script_or_style.decompose()
        

    text = soup.get_text(separator="\n")

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    clean_text = " ".join(lines)
    return clean_text

In [4]:
def seed_chunks_by_tokens(text, model_name="gpt-4o", chunk_size=500, chunk_overlap=50):

    encoding = tiktoken.encoding_for_model(model_name)
    
    all_tokens = encoding.encode(text)
    
    chunks = []

    for i in range(0, len(all_tokens), chunk_size - chunk_overlap):

        chunk_tokens = all_tokens[i : i + chunk_size]
        chunk_text = encoding.decode(chunk_tokens)
        chunks.append(chunk_text)
        
    return chunks

In [5]:
chunk_size = 100
chunk_overlap = 20
chunks = []
url1 = "https://www.azfamily.com/2024/07/01/evacuation-orders-lifted-boulder-view-fire-near-scottsdale-63-contained/"
url2 = "https://www.kjzz.org/news/2024-06-28/60-forced-to-evacuate-from-boulder-view-fire-in-north-scottsdale"

content1 = get_content(url1)
chunks1 = seed_chunks_by_tokens(content1, chunk_size=chunk_size, chunk_overlap=chunk_overlap)

content2 = get_content(url2)
chunks2 = seed_chunks_by_tokens(content2, chunk_size=chunk_size, chunk_overlap=chunk_overlap)



for c in chunks1:
    chunks.append({'content': c, "source_url": url1})

for c in chunks2:
    chunks.append({'content': c, "source_url": url2})

In [6]:
print(chunks[0])

{'content': 'Boulder View Fire 95% contained near Scottsdale Skip to content Share Add Us On Google Add as a preferred source on Google SCOTTSDALE, AZ (AZFamily) — The Boulder View Fire, which has burned thousands of acres northwest of Scottsdale, is now 95% contained as of July 4. The Boulder View Fire first sparked on June 27 and has burned 3,711 acres. The fire hasn’t grown in acreage for days. The #BoulderViewFire is', 'source_url': 'https://www.azfamily.com/2024/07/01/evacuation-orders-lifted-boulder-view-fire-near-scottsdale-63-contained/'}

In [7]:
client = weaviate.connect_to_local(
    headers={"X-OpenAI-Api-Key": os.getenv("OPENAI_API_KEY")}
)
client.connect()

In [8]:
collection_name = "NewsChunk"

# client.collections.delete(collection_name)

if not client.collections.exists(collection_name):
    client.collections.create(
        name=collection_name,
        vector_config=[wvc.Configure.Vectors.text2vec_openai(
            name='core', 
            source_properties=['content'],
            model='text-embedding-3-large',
            dimensions=1024
        )],
        properties=[
            wvc.Property(name="content", 
                         data_type=wvc.DataType.TEXT),
            wvc.Property(name="source_url", 
                         data_type=wvc.DataType.TEXT)
        ]
    )
    news_chunks = client.collections.get(collection_name)
    with news_chunks.batch.dynamic() as batch:
        for c in chunks:
            batch.add_object(
                properties={
                    "content": c['content'],
                    "source_url": c['source_url']
                }
            )
    print(f"successfully stored {len(chunks)} data points")
news_chunks = client.collections.use(collection_name)

In [9]:
def RAG_Q_A(question, vector_database, LLM_clinet, model_name):
    response = vector_database.query.near_text(
    query=question,
    limit=3)

    retrieved_content = ''
    for obj in response.objects:
        retrieved_content += obj.properties['content'] + '\n'
        # print(retrieved_content)
        
    augmented_question = augmented_question_template.format(question=question, retrieved_content=retrieved_content)

    response = LLM_client.responses.create(
        model = model_name,
        input = augmented_question
        )

    return response.output_text, retrieved_content

In [10]:
augmented_question_template = '''
You will need to answer my question based on the information I give you,

This is the question:
{question}

This is the background information:
{retrieved_content}
'''

LLM_client = OpenAI()
model_name = 'gpt-4.1-mini'

In [11]:
question = "What roads or areas were affected (closed or restricted) during the fire, and which of them were later reopened?"
answer, retrieved_content = RAG_Q_A(question, news_chunks, LLM_client, model_name)

In [12]:
print(answer)

Based on the information provided:

**Roads or areas affected (closed or restricted) during the fire:**
- The north part of the McDowell Sonoran Preserve, including all trails and access points north of Dynamite Boulevard, was closed until further notice.
- Residents in the evacuation zone, specifically from 136th Street to Box Bar Road and Rio Verde Road to Dove Valley, were told to evacuate.
- Evacuation orders also affected around 60 homes.

**Roads or areas later reopened:**
- All trailheads in the north part of the McDowell Sonoran Preserve were reopened on Monday morning.
- Bartlett Lake Dam Road and Horseshoe Dam Road were reopened on Monday morning.
- Evacuation orders for the residents from 136th Street to Box Bar Road and Rio Verde Road to Dove Valley were lifted on Saturday afternoon, allowing them to return to "READY" status.

In summary, the north part of McDowell Sonoran Preserve trails and access points, Bartlett Lake Dam Road, and Horseshoe Dam Road were closed during the fire but have since been reopened. Evacuations affecting specific neighborhoods were also lifted following containment progress.

In [13]:
print(retrieved_content)

 out of everyone’s way and help where I can,” said Engelker. The City of Scottsdale notified homeowners that the north part of the McDowell Sonoran Preserve, including all trails and access points north of Dynamite Boulevard, would be closed until further notice. All trailheads were reopened Monday morning. Bartlett Lake Dam Road and Horseshoe Dam Road were reopened Monday morning. Tiffany Davila, spokeswoman with the Department of Forestry and Fire Management, says around 60 homes were evacuated. The fire also
 statuses for those near the fire. This means that residents in the evacuation zone are returning to “READY” status as crews made progress on the fire. On Friday, residents in the area from 136th Street to Box Bar Road and Rio Verde Road to Dove Valley were told to evacuate as the fire grew closer to their neighborhood. Those evacuation orders were lifted on Saturday afternoon. “We were woken up by a police helicopter with spotlights in our area on the radio asking everybody to evacuate
11:46 AM MST Facebook Threads LinkedIn Bluesky Email Listen • 0:34 DFFM/Inciweb DFFM Tucson crew members working the southeast side of the fire on June 27, 2024. July 1, 2024: Blaze is 63% contained, evacuations lifted Evacuation orders in Arizona have been lifted for some residents of northeast Scottsdale, days after they were forced from their homes by a wildfire, authorities said Sunday. The Boulder View Fire

In [14]:
question = "At the beginning of the wildfire (June 28), where did evacuations occur and how many people (or homes) were evacuated?"
answer, retrieved_content = RAG_Q_A(question, news_chunks, LLM_client, model_name)

In [15]:
print(answer)

At the beginning of the wildfire on June 28, evacuations occurred in part of the Vista Verde community, which is a subdivision on the edge of the Tonto National Forest. Approximately 60 homes were evacuated, with around 60 people having left their homes by Friday morning after Maricopa County emergency personnel ordered the evacuations. Additionally, residents between 136th Street to Box Bar Road and Rio Verde to Dove Valley roads were advised to be prepared for evacuation.

In [16]:
print(retrieved_content)

 with the Department of Forestry and Fire Management, says around 60 homes were evacuated. The fire also threatened power lines in the area. “It’s very uneasy knowing that anything could happen at any moment. The wind shifts and fire was moving in one direction last night and then it shifted in the middle of the night, so here we are,” said Engelker. On the night it began, the southeast end of the fire grew significantly, prompting evacuations for part of the Vista Verde community. “
 60 people had left their homes by Friday morning after Maricopa County emergency personnel ordered evacuations for the subdivision on the edge of the Tonto National Forest. The Maricopa County Department of Emergency Management on Friday expanded the list of who needs to get set to evacuate. As of Friday morning, residents between 136th Street to Box Bar Road and Rio Verde to Dove Valley roads should be prepared. Fire officials said they were investigating exactly what sparked the blaze. Nearly 200 firefighters were
11:46 AM MST Facebook Threads LinkedIn Bluesky Email Listen • 0:34 DFFM/Inciweb DFFM Tucson crew members working the southeast side of the fire on June 27, 2024. July 1, 2024: Blaze is 63% contained, evacuations lifted Evacuation orders in Arizona have been lifted for some residents of northeast Scottsdale, days after they were forced from their homes by a wildfire, authorities said Sunday. The Boulder View Fire

In [20]:
f1_path = r"/home/huihai/Huihai/interview/interviewRAG/graphrag/input/news1.txt"
f2_path = r"/home/huihai/Huihai/interview/interviewRAG/graphrag/input/news2.txt"

with open(f1_path, "w") as txt_file1:
    txt_file1.write(content1)

with open(f2_path, "w") as txt_file2:
    txt_file2.write(content2)

In [21]:
import pandas as pd

In [50]:
entities = pd.read_parquet(r"/home/huihai/Huihai/interview/interviewRAG/graphrag/output/entities.parquet")
relationships = pd.read_parquet(r"/home/huihai/Huihai/interview/interviewRAG/graphrag/output/relationships.parquet")
communities = pd.read_parquet(r"/home/huihai/Huihai/interview/interviewRAG/graphrag/output/communities.parquet")
communities_reports = pd.read_parquet(r"/home/huihai/Huihai/interview/interviewRAG/graphrag/output/community_reports.parquet")

In [51]:
entities['description'][32]

'Cave Creek Road is located near the Boulder View Fire.'

In [52]:
entities

,id,human_readable_id,title,type,description,text_unit_ids,frequency,degree,x,y
0,0e319622-6b8b-4ca3-8cd3-2af4e4a56b06,0,BOULDER VIEW FIRE,FIRE_EVENT,The Boulder View Fire is a significant wildfir...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2,28,0.0,0.0
1,1af61b5a-9518-46df-bbcc-4887dfd55988,1,NORTH SCOTTSDALE,FIRE_LOCATION,North Scottsdale is the geographic area where ...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
2,7b1355ae-d180-4775-b670-1ba36a363cec,2,HUMAN-CAUSED,FIRE_CAUSE,The Boulder View Fire is identified as a human...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2,1,0.0,0.0
3,ef2bb11a-ab1d-4a64-bf92-f46877fac62c,3,STATUS_JUNE28_1146,STATUS,"As of June 28, 2024, at 11:46 AM MST, the Boul...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,2,0.0,0.0
4,e175825a-2a24-4039-9a13-e1e7c6d3105c,4,3711 ACRES,BURNED_AREA,"As of June 28, 2024, the Boulder View Fire has...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2,1,0.0,0.0
5,48a955f3-a3ae-41f5-a994-b70c197415af,5,60 HOMES EVACUATED,EVACUATION_DETAIL,"On June 27, 2024, evacuation orders were issue...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2,1,0.0,0.0
6,b1f66f3c-b438-4691-84ca-28015208292c,6,270 FIREFIGHTERS,EMERGENCY_RESPONSE,Nearly 270 firefighters are actively battling ...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
7,095d502d-57c9-46c6-9cba-658a57c130df,7,NO INJURIES REPORTED,PUBLIC_SENTIMENT,"As of the latest reports, no injuries have bee...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
8,4796c73c-4422-4ddc-9086-b86f9234c483,8,ZERO PERCENT CONTAINMENT,CONTAINMENT_STATUS,"As of June 29, 2024, the Boulder View Fire is ...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,0,NaN,NaN
9,d520edab-5b5a-4e6e-9f9a-dbb0e551e4bb,9,GO TO SET,EVACUATION_DETAIL,Evacuation orders were lowered from “GO” to “S...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
10,11b8f7bc-8205-467d-960c-d50f09a8e5d7,10,MCDOWELL SONORAN PRESERVE,FIRE_LOCATION,The McDowell Sonoran Preserve is a geographic ...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
11,5597cade-c5a0-4782-bb00-1a901882d1df,11,CAVE CREEK,FIRE_LOCATION,Cave Creek is a nearby location where evacuati...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
12,6e20f5ea-3959-4d37-ad52-3032fa2445b3,12,TRIPLE-DIGIT HEAT,PUBLIC_SENTIMENT,The firefighting efforts are taking place in t...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
13,867b9021-f70e-422b-b748-7917fc1029c4,13,STATUS_JUNE29_2024,,,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
14,668114da-41d7-4f70-ad60-67c251981e56,14,NATIONAL INTERAGENCY FIRE CENTER,FIRE_EVENT,The National Interagency Fire Center is coordi...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,8,0.0,0.0
15,2eb35404-c40b-44a1-b425-de7e34f4dbf5,15,ALASKA,FIRE_LOCATION,Alaska is one of the states currently experien...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
16,3cbea1f3-6168-42f4-85a2-bddae89411c5,16,OREGON,FIRE_LOCATION,Oregon is one of the states currently experien...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
17,a4af808c-db4d-4fc8-b814-8079bb5e0f4b,17,CALIFORNIA,FIRE_LOCATION,California is one of the states currently expe...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
18,3a01176b-d266-4f49-91b0-2cf25df68dbb,18,NEW MEXICO,FIRE_LOCATION,New Mexico is one of the states currently expe...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
19,095f5067-ad88-4a5e-8933-57ab65f535c2,19,WASHINGTON,FIRE_LOCATION,Washington is one of the states currently expe...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
20,823f7132-aac0-48f3-9561-ec7c6be7778f,20,AIR TANKERS,EMERGENCY_RESPONSE,Air tankers armed with red retardant are being...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,2,0.0,0.0
21,58bd1d0d-8f92-409d-9f7a-f17f7dbbdb68,21,HELICOPTERS,EMERGENCY_RESPONSE,Helicopters hauling giant buckets of water are...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,2,0.0,0.0
22,8b44592a-958c-4151-aef8-3450be6de0d9,22,FLAMES,FIRE_EVENT,Flames are the visible part of the fire that i...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
23,64adcbb9-c23b-4579-b854-73c3ae2ec848,23,POWER LINES,FIRE_LOCATION,Power lines are infrastructure that is being p...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
24,ee30ffed-c856-4e55-afa9-6cdb2a404410,24,RED RETARDANT,EMERGENCY_RESPONSE,Red retardant is a chemical used by air tanker...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
25,6aba2262-7f43-43d7-889b-21eb7e45a36a,25,GIANT BUCKETS OF WATER,EMERGENCY_RESPONSE,Giant buckets of water are used by helicopters...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
26,dd363271-2f6a-48d3-bbe7-3738fce68f55,26,FIRE OFFICIALS,,,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,1,0.0,0.0
27,765cfe52-0df4-4739-a90f-07d07c97e7ed,27,SCOTTSDALE,FIRE_LOCATION,Scottsdale is the location where the Boulder V...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
28,21b1467f-5b89-41df-bd04-9ab9cbcd919a,28,STATUS_JULY4,STATUS,"As of July 4, the Boulder View Fire is 95% con...",[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
29,ee936e7a-a3ff-47cb-9ae7-6feec62ddf27,29,EMERGENCY RESPONSE,EMERGENCY_RESPONSE,The Arizona Department of Forestry and Fire Ma...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
30,38eb9eff-1760-4e0a-bff4-4aa25a8b34c9,30,PUBLIC SENTIMENT,PUBLIC_SENTIMENT,Residents expressed unease and concern about t...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
31,13b4e460-8944-4d4f-aacd-ffc4bbbb1615,31,LONE MOUNTAIN PARKWAY,FIRE_LOCATION,Lone Mountain Parkway is located near the Boul...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
32,5c430f16-0934-4a93-9a9d-c594856d81ed,32,CAVE CREEK ROAD,FIRE_LOCATION,Cave Creek Road is located near the Boulder Vi...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
33,0e4d51ff-f2cc-4172-be6e-1ec3bcd8a52d,33,DESERT MOUNTAIN GOLF CLUB,FIRE_LOCATION,Desert Mountain Golf Club is located east of t...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
34,6f4ce7a7-f19a-4a6b-a09b-007b8b89dd9d,34,CAVE CREEK MEMORIAL ARENA,FIRE_LOCATION,Cave Creek Memorial Arena is a large animal ev...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
35,0d9b3bfe-c0fd-48b7-afe9-18a75a4738ee,35,REIGNING GRACE RANCH,FIRE_LOCATION,Reigning Grace Ranch is another large animal e...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
36,b8690e88-35f3-458a-8e14-cc485be08237,36,CAVE CREEK OUTFITTERS,FIRE_LOCATION,Cave Creek Outfitters is also a large animal e...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
37,f06bc81e-2116-4443-86cd-15eb1f27f066,37,SET STATUS,STATUS,The Maricopa County Department of Emergency Ma...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
38,e6f91977-5090-4834-b5ec-ad54acab5a22,38,READY STATUS,STATUS,Residents in the evacuation zone returned to “...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
39,b7dc6439-1b23-406e-b603-138ecc509a0a,39,TIFFANY DAVILA,PERSON,Tiffany Davila is a spokeswoman with the Depar...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
40,96d54c30-6426-48f6-b58d-2936e5de2ea6,40,KRISTIN ENGELKER,PERSON,Kristin Engelker is a resident who described h...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
41,d126b76c-ce7f-4b06-ad9d-cfe32069761a,41,MADDISON BACA,PERSON,Maddison Baca is a resident who shared her con...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
42,601309d3-62d2-4011-a661-1459369e97d4,42,BRYAN CHURCH,PERSON,Bryan Church is the co-owner of Bartlett Lake ...,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
43,103d9b61-7d73-4d38-8d12-e4ca8c724605,43,BOULDER HEIGHTS,,,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,1,1,0.0,0.0
44,0d3cce5f-69d1-4574-ab40-f4e1f6ad8dcf,44,HAZARDOUS AIR QUALITY,FIRE_EVENT,Hazardous air quality reported east of Phoenix...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,4,0.0,0.0
45,ac913fa2-a037-4036-a91f-8966b9e17fa9,45,PHOENIX METRO,FIRE_LOCATION,The Phoenix metro area is experiencing hazardo...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,2,0.0,0.0
46,9e3650ad-cb54-4e74-a8f3-16bc95b1be11,46,DUST,FIRE_CAUSE,Dust contributing to hazardous air quality in ...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
47,4003c6ca-8d4f-4adb-b04a-8423bda2ecec,47,SMOKE,FIRE_CAUSE,Smoke contributing to hazardous air quality in...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
48,4c651982-158d-4dec-aaf9-69f64b858c04,48,POLLEN,FIRE_CAUSE,Pollen contributing to hazardous air quality i...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
49,d5141e40-8ea7-4f88-b3d7-deef158aaf69,49,HOME WARRANTY SETTLEMENT,FIRE_EVENT,A settlement of $11.8 million related to home ...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
50,e414fbf3-d079-400e-8b35-666142281576,50,WATERFALL,FIRE_LOCATION,A location in central Arizona where a man drow...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
51,faa74c06-008f-4937-9472-d01aa5c148d5,51,CENTRAL ARIZONA,FIRE_LOCATION,Region where the drowning incident occurred,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
52,26ebb808-1fe5-4977-8b3d-a09d92bbca81,52,D-BACKS HOME OPENER,FIRE_EVENT,The D-backs home opener event where a remarkab...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,2,0.0,0.0
53,9d88bec0-b79d-47e9-91c2-5dc5262a24a2,53,WOMEN’S FINAL FOUR,FIRE_EVENT,Event related to the championship weekend in P...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
54,de54ceb2-0ad3-4551-be7e-48b6dbc62f96,54,LITTLE LEAGUER,FIRE_EVENT,A young baseball player who overcame septic sh...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
55,44a93ec5-7da0-47ad-a547-04dde5e20b24,55,AIR POLLUTION,FIRE_CAUSE,Air pollution impacting breathing in the Phoen...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
56,153be71b-3459-4115-aed2-2c3342396ac7,56,AG,,,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0

In [28]:
entities[entities['type'] == "EVENT"]

,id,human_readable_id,title,type,description,text_unit_ids,frequency,degree,x,y
0,048db1c0-12c9-4496-8f9f-a2246f80307b,0,BOULDER VIEW FIRE,EVENT,The Boulder View Fire is a significant wildfir...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2,14,0.0,0.0
7,e1d8b5bd-2827-42b4-a3bc-c492e0577cd9,7,WILDCAT FIRE,EVENT,The Wildcat Fire is a previous wildfire that m...,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,1,1,0.0,0.0
17,b018d688-76ac-4f7b-8618-5df5284560cf,17,WILDFIRES,EVENT,Wildfires are large uncontrolled fires that ar...,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...,1,6,0.0,0.0
34,85257bdd-38c3-4e99-9fa1-57752412986a,34,WOMEN'S FINAL FOUR,EVENT,The Women's Final Four is a championship weeke...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
36,94fe4991-f0b5-4449-b931-f1cfaffb0dd2,36,NATIONAL ANTHEM,EVENT,A performance of the national anthem at the D-...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
38,8c07f5fb-2a87-45d6-beb5-26f15484cae0,38,D-BACKS HOME OPENER,EVENT,The D-backs home opener is a significant event...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0
39,f93a9a32-ff96-4a8f-90b6-23f8a5e933e3,39,HAZARDOUS AIR QUALITY,EVENT,Hazardous air quality is an environmental even...,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...,1,1,0.0,0.0

In [31]:
relationships['description'][0]

'The Boulder View Fire is a significant wildfire located near Scottsdale, Arizona, directly impacting the city and its residents. The fire has prompted evacuations and necessitated emergency responses to ensure the safety of those in the affected areas. As the situation develops, local authorities are actively managing the fire and coordinating efforts to protect the community from its effects. The ongoing response highlights the urgency of the situation and the commitment of emergency services to safeguard the residents of Scottsdale during this challenging time.'

In [53]:
relationships

,id,human_readable_id,source,target,description,weight,combined_degree,text_unit_ids
0,271d2fef-50cd-43a8-91b6-da5631cfb391,0,BOULDER VIEW FIRE,NORTH SCOTTSDALE,The Boulder View Fire is located in North Scot...,9.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
1,a38dff2d-701f-4e10-8210-58d16f58e187,1,BOULDER VIEW FIRE,HUMAN-CAUSED,The Boulder View Fire is an incident that is b...,17.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
2,e17b193c-fc4f-439a-8277-4851e33639a1,2,BOULDER VIEW FIRE,STATUS_JUNE28_1146,The status of the Boulder View Fire as of June...,7.0,30,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
3,e99ab2e0-e092-4aba-82a4-90991acbeee4,3,BOULDER VIEW FIRE,3711 ACRES,The Boulder View Fire has significantly impact...,16.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
4,d4cad18b-98bd-42db-b8a7-ac91298eb1b5,4,BOULDER VIEW FIRE,60 HOMES EVACUATED,The Boulder View Fire prompted the evacuation ...,16.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
5,c5704131-384b-46d1-adc9-5754a922c7d6,5,BOULDER VIEW FIRE,270 FIREFIGHTERS,The presence of nearly 270 firefighters is a d...,9.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
6,991e62c7-8bf7-42f1-8b51-d816033fc5b4,6,BOULDER VIEW FIRE,NO INJURIES REPORTED,The report of no injuries related to the Bould...,1.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
7,5143f501-b26f-4eba-b216-5d7122d63821,7,BOULDER VIEW FIRE,STATUS_JUNE29_2024,The status of the Boulder View Fire as of June...,7.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
8,83f56856-2df5-4558-b6fd-33b6328d7d12,8,BOULDER VIEW FIRE,MCDOWELL SONORAN PRESERVE,The McDowell Sonoran Preserve has been closed ...,7.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
9,a623a585-ff3f-4523-a885-f7c7cc017638,9,BOULDER VIEW FIRE,CAVE CREEK,Evacuation shelters for large animals were est...,6.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
10,81ad1d38-65db-4ec3-809f-47492711c019,10,BOULDER VIEW FIRE,TRIPLE-DIGIT HEAT,The firefighting efforts for the Boulder View ...,1.0,29,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
11,934bac59-4218-47fc-8a11-b377d01f9276,11,STATUS_JUNE28_1146,GO TO SET,The lowering of evacuation orders from “GO” to...,6.0,3,[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...
12,a18a945d-880c-4b79-9756-6bf92e7b6b2b,12,NATIONAL INTERAGENCY FIRE CENTER,ALASKA,The National Interagency Fire Center is coordi...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
13,48af4547-3f39-4873-adf7-636203cb2e7a,13,NATIONAL INTERAGENCY FIRE CENTER,OREGON,The National Interagency Fire Center is coordi...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
14,e68c2e80-1f61-4e5c-a473-133cb0047a31,14,NATIONAL INTERAGENCY FIRE CENTER,CALIFORNIA,The National Interagency Fire Center is coordi...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
15,fa76b043-b151-4358-b042-3fd425a6314e,15,NATIONAL INTERAGENCY FIRE CENTER,NEW MEXICO,The National Interagency Fire Center is coordi...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
16,93d72eb1-b49c-410a-8627-f4ff6e9cb7dd,16,NATIONAL INTERAGENCY FIRE CENTER,WASHINGTON,The National Interagency Fire Center is coordi...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
17,cc824f9a-3e2b-454f-ab87-03a43d0e704d,17,NATIONAL INTERAGENCY FIRE CENTER,AIR TANKERS,Air tankers are part of the emergency response...,8.0,10,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
18,fa37c63a-c14b-4318-8047-b063be6ba104,18,NATIONAL INTERAGENCY FIRE CENTER,HELICOPTERS,Helicopters are part of the emergency response...,1.0,10,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
19,92f88259-e9f1-4476-b743-2b874ba4c2b5,19,NATIONAL INTERAGENCY FIRE CENTER,FIRE OFFICIALS,Fire officials are working under the coordinat...,7.0,9,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
20,187b8494-d085-4cf1-8c35-98d5846db3de,20,AIR TANKERS,RED RETARDANT,Air tankers are using red retardant to suppres...,8.0,3,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
21,c70a9640-822b-43b7-bed9-243e49013b39,21,HELICOPTERS,GIANT BUCKETS OF WATER,Helicopters are utilizing giant buckets of wat...,1.0,3,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
22,66921c78-6e8c-4d72-9b20-5c0071341ef0,22,FLAMES,POWER LINES,"Flames are threatening the power lines, prompt...",6.0,2,[fc9c4bed00823db3f384e37e47892d5b31a40188d14b6...
23,b6ee9ec2-2701-4fd2-a15b-51042c02abec,23,BOULDER VIEW FIRE,SCOTTSDALE,The Boulder View Fire is located northwest of ...,8.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
24,c94d9d26-b003-434a-adad-ad503d55fea7,24,BOULDER VIEW FIRE,STATUS_JULY4,"As of July 4, the Boulder View Fire is 95% con...",8.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
25,f43b3d7c-b4bd-4159-9a8d-06477d4f07b2,25,BOULDER VIEW FIRE,EMERGENCY RESPONSE,Emergency response teams are actively engaged ...,8.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
26,1cbf7bed-64a4-495d-91e6-caa8f42c2a79,26,BOULDER VIEW FIRE,PUBLIC SENTIMENT,Residents expressed concern about the Boulder ...,1.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
27,703e84e3-fa2b-44a7-a5da-2968f5907b2e,27,BOULDER VIEW FIRE,BOULDER HEIGHTS,Boulder Heights is a community near the Boulde...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
28,84e7ec75-070a-4850-9416-208db575dfce,28,BOULDER VIEW FIRE,LONE MOUNTAIN PARKWAY,Lone Mountain Parkway is located near the Boul...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
29,01d45d55-fc56-42d7-9cb8-0756ee8baae2,29,BOULDER VIEW FIRE,CAVE CREEK ROAD,Cave Creek Road is located near the Boulder Vi...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
30,36dc88aa-7ebc-4dc3-8d47-c7303f068abb,30,BOULDER VIEW FIRE,DESERT MOUNTAIN GOLF CLUB,Desert Mountain Golf Club is located east of t...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
31,9eb4beac-fc1b-4329-bbde-750800eba0c0,31,BOULDER VIEW FIRE,CAVE CREEK MEMORIAL ARENA,Cave Creek Memorial Arena is a shelter for pet...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
32,c3f3f54f-00bf-4ecf-aae3-7e3316e63fb8,32,BOULDER VIEW FIRE,REIGNING GRACE RANCH,Reigning Grace Ranch is a shelter for pets eva...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
33,bbe9e253-d798-490e-937b-fb59a50fc0f7,33,BOULDER VIEW FIRE,CAVE CREEK OUTFITTERS,Cave Creek Outfitters is a shelter for pets ev...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
34,5e187810-dfa4-436c-8889-15ac3e9cae11,34,BOULDER VIEW FIRE,SET STATUS,The Boulder View Fire led to the lifting of “S...,6.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
35,653b18b7-6f0f-41c6-b12b-6865267cd179,35,BOULDER VIEW FIRE,READY STATUS,Residents returned to “READY” status as crews ...,6.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
36,30abc603-9a86-40f4-b839-168ca5d9e91b,36,BOULDER VIEW FIRE,TIFFANY DAVILA,Tiffany Davila provided updates on the Boulder...,8.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
37,3d5415fa-97f7-419e-83fd-f81c1c91c9ac,37,BOULDER VIEW FIRE,KRISTIN ENGELKER,Kristin Engelker described her experience duri...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
38,204bad65-6cf6-4436-80e5-9be44d71aaf7,38,BOULDER VIEW FIRE,MADDISON BACA,Maddison Baca shared her concerns and preparat...,7.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
39,5223e625-73a8-4ae0-baed-47756c55255d,39,BOULDER VIEW FIRE,BRYAN CHURCH,Bryan Church commented on the impact of the Bo...,1.0,29,[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...
40,4b8fd656-224a-4d43-8408-ed34f42b1000,40,HAZARDOUS AIR QUALITY,PHOENIX METRO,Hazardous air quality is reported in the Phoen...,8.0,6,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
41,cde4bd43-b21e-49b6-92c5-83e26e15f311,41,HAZARDOUS AIR QUALITY,DUST,Dust is a cause of the hazardous air quality,7.0,5,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
42,73ae62ca-d0b5-4549-94a6-5ce9a4d50b9c,42,HAZARDOUS AIR QUALITY,SMOKE,Smoke is a cause of the hazardous air quality,7.0,5,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
43,3f7ba990-4e11-459a-9763-d6b6731983b3,43,HAZARDOUS AIR QUALITY,POLLEN,Pollen is a cause of the hazardous air quality,1.0,5,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
44,20006878-633e-4f78-b7b8-cc5b9190932a,44,PHOENIX METRO,AIR POLLUTION,Air pollution is affecting the breathing condi...,1.0,3,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
45,b2259286-0628-4cd0-a93d-e67124151d4d,45,HOME WARRANTY SETTLEMENT,AG,AG is urging consumers to claim their share of...,6.0,2,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
46,254f2cc5-678c-439b-bfb7-3890bc82b560,46,WATERFALL,CENTRAL ARIZONA,The drowning incident occurred at a waterfall ...,8.0,2,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
47,be35736a-4776-4c27-b2df-92c6e6d82568,47,D-BACKS HOME OPENER,WOMEN’S FINAL FOUR,The D-backs home opener is part of the events ...,5.0,3,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...
48,f6c7b925-e2d1-4ee8-8cce-d5df5123b3df,48,D-BACKS HOME OPENER,LITTLE LEAGUER,The Little Leaguer threw the first pitch at th...,7.0,3,[364e4088f0a43d3aec204b2e79f94a5686f99429496a9...

In [34]:
communities

,id,human_readable_id,community,level,parent,children,title,entity_ids,relationship_ids,text_unit_ids,period,size
0,fcd39395-29f1-4936-a7a8-d2feca4d9eb7,0,0,0,-1,"[2, 3]",Community 0,"[b7785036-c474-414f-a234-968d8dacfacc, 048db1c...","[0b7415ee-168d-46be-9481-68fd7de49cc6, 0fefc66...",[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,2026-03-30,15
1,08367477-7640-4324-b863-fff48bf23fc8,1,1,0,-1,[],Community 1,"[8efd67bd-8b7b-499a-8206-3560dc7ef387, ed8405c...","[08d529b0-bc94-4cc8-946a-a39fc78f91cd, 64e1eca...",[e6d6debbae3b1b433e35944390c1e13f0a90b7715b5d7...,2026-03-30,3
2,40a32584-53f5-42fc-90d7-d1a6c971d74c,2,2,1,0,[],Community 2,"[048db1c0-12c9-4496-8f9f-a2246f80307b, 3e520ae...","[0b7415ee-168d-46be-9481-68fd7de49cc6, 0fefc66...",[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,2026-03-30,13
3,693f540a-8fc8-4e24-9ee3-0bae3913e410,3,3,1,0,[],Community 3,"[b7785036-c474-414f-a234-968d8dacfacc, bc29c07...","[8011211c-85d2-40f8-a7f0-268354bcabff, afaac08...",[d041353774cdf4d3b2fc64b76a3e20e5f21b950f2093b...,2026-03-30,2